from typing import Tuple, List
from .basic_darp_negotiator import BasicDARPNegotiator
from .. import BasicDARPClient
from ..outcome import BasicDARPOutcome
import random
import numpy as np


class SingleTextBasicNegotiator(BasicDARPNegotiator):
    """
    Implementation of BasicDARPNegotiator for the single text mediated negotiation protocol.
    In this protocol, negotiators respond to proposals generated by the mediator.
    """

    def __init__(self, agent_id: str, problem):
        super().__init__(agent_id, problem)
        self.utility_threshold = 0 
        self.utility_change = 0
        
    def prepare_prenegotiation(self):
        """
        Prepare for the pre-negotiation phase by determining which
        clients the agent is willing to share.
        Internal method before 
        """
        # TODO: Implement a more sophisticated client selection strategy before calling reveal_client()
        # By default, share all clients
        pass
        
    def prepare_negotiation(self):
        """
        Prepare for the negotiation phase by setting utility thresholds
        or other negotiation parameters.
        """
        return
        
    def reveal_client(self) -> List[BasicDARPClient]:
        """
        Reveal a client that this agent is willing to negotiate over.
        Returns the client with the highest associated cost.
        """
        my_costs = [self.get_associated_cost([c.client_id]) for c in self.darp_problem.clients.values()]
        avg_cost = np.mean(my_costs)
        std_cost = np.std(my_costs)
        cv = std_cost / avg_cost  # Coefficient of variation
        
        # If costs are very variable (high CV), be more conservative
        # If costs are similar (low CV), can share more
        if cv > 0.5:  # High variability
            threshold = avg_cost + (0.8 * std_cost)  # More conservative
        elif cv > 0.3:  # Medium variability
            threshold = avg_cost + (1.0 * std_cost)  # Standard
        else:  # Low variability
            threshold = avg_cost + (1.2 * std_cost)  # More generous
        
        outliers = [c for c in self.darp_problem.clients.values() 
                   if self.get_associated_cost([c.client_id]) > threshold]
        
        if not outliers:
            return [max(self.darp_problem.clients.values(), 
                       key=lambda c: self.get_associated_cost([c.client_id]))]
        
        return outliers[:max(1, len(self.darp_problem.clients) // 2)]

    def propose_bid(self, **kwargs) -> BasicDARPOutcome:
        """
        In this implementation, the agent doesn't directly propose bids
        as the mediator handles proposal generation.
        """
        pass  # No outcome - not used in single text mediation
        
    def receive_response(self, outcome: BasicDARPOutcome, agent: str, response: bool, **kwargs):
        """
        Record responses from other agents to the current proposal.
        """
        pass # Not used in single text mediation
        
    def is_acceptable(self, outcome: BasicDARPOutcome, **kwargs) -> Tuple[bool, float]:
        """
        Determine if a proposed outcome is acceptable to this agent.
        Returns:
            - A boolean indicating if the utility change meets or exceeds the threshold.
            - The calculated utility change value.
        """
        # TODO: improve threshold calculation (maybe dynamic) or use a different approach
        giving = []
        getting = []        
        for client_id, owner_id in outcome.items():
            current_owner = self._client_owners.get(client_id)
            if current_owner == self.agent_id and owner_id != self.agent_id:
                giving.append(client_id)
            elif current_owner != self.agent_id and owner_id == self.agent_id:
                getting.append(client_id)
        temp_utility = self.get_utility(including=getting, excluding=giving)
        # Persist delta so update_agreement() can commit the accepted proposal.
        self.utility_change = temp_utility - self.current_utility
        is_accepted = temp_utility <= self.current_utility
        
        # Concise decision summary
        exchange_summary = ""
        if giving and getting:
            exchange_summary = f" (give {giving}, get {getting})"
        elif giving:
            exchange_summary = f" (give {giving})"
        elif getting:
            exchange_summary = f" (get {getting})"
        
        if is_accepted:
            emoji, decision = "✅", "ACCEPT"
        else:
            emoji, decision = "❌", "REJECT"
        print(f"{emoji} Agent {self.agent_id}: {decision} - new utility {temp_utility:.0f}{exchange_summary}")
        
        return is_accepted, temp_utility
